# Generated by Django 5.0.6 on 2024-07-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTiendita', '0005_alter_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='carrito',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
