# Generated by Django 5.0.6 on 2024-07-15 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTiendita', '0006_rename_cliente_carrito_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTiendita.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_despacho', models.CharField(max_length=50)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_compra', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='producto',
            field=models.ManyToManyField(to='LaTiendita.producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTiendita.producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTiendita.userprofile'),
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
